### ISSUE TITLE
rlapi fails when playlist's data is full of nulls

### ISSUE THREAD

**Issue by jack1142** [jack1142/rlapi#28]
### Reproduction Steps

```py
import asyncio
from rlapi import Client, Platform

loop = asyncio.get_event_loop()

token = ...
client = Client(token)
player = loop.run_until_complete(client.get_player("Snuf", Platform.ps4))
```

### Expected Results

Get player stats

### Actual Results

I got error:
```
Traceback (most recent call last):
  File "/home/ubuntu/red-venv/lib/python3.8/site-packages/redbot/core/dev_commands.py", line 171, in _eval
    result = await func()
  File "<string>", line 10, in func
  File "/home/ubuntu/red-local/cogs/Downloader/lib/rlapi/client.py", line 173, in get_player
    return (await self._get_stats(player_id, platform),)
  File "/home/ubuntu/red-local/cogs/Downloader/lib/rlapi/client.py", line 141, in _get_stats
    return Player(
  File "/home/ubuntu/red-local/cogs/Downloader/lib/rlapi/player.py", line 193, in __init__
    self.highest_tier = max(
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- rlapi version: 0.2.0a1
- Python version: 3.8.1
- Operating system: Ubuntu 18.04 LTS

**Comment by jack1142** [comment]
Update: Got a response from Dirkened that API may return such playlist data in response if player haven't played any placement matches in this season yet.
